# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dynamic_obstacles/TrackedObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import dynamic_obstacles.msg
import geometry_msgs.msg
import uuid_msgs.msg

class TrackedObject(genpy.Message):
  _md5sum = "ab8923e41e784db52548f8423530ee07"
  _type = "dynamic_obstacles/TrackedObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# TrackedObject.msg

# ============================================================
# 坐标系与时间规范
#
# 1. 本消息自身不包含 Header，所有目标统一使用
#    TrackedObjectArray.header 中的时间戳和参考坐标系。
#
# 2. 本项目规定：
#    TrackedObjectArray.header.frame_id 必须为 "map"或"odom"。
#
# 3. pose、twist 和 acceleration 均对应
#    TrackedObjectArray.header.stamp 所表示的统一状态时刻。
#
# 4. 以下物理量均在 指定参考的 坐标系上表达：
#    - pose.position 底面中心点
#    - pose.orientation 表示目标局部坐标系到 指定参考的 坐标系的旋转
#    - twist.linear
#    - twist.angular
#    - acceleration.linear
#    - acceleration.angular
#
# 5. twist 和 acceleration 表示经过机器人自身运动补偿后的、
#    目标相对于 指定参考的 坐标系的估计运动状态，
#    不是相对机器人或相对传感器的运动状态。
#
# 6. 目标局部坐标系基础约定：
#   - 原点位于目标底面几何中心，右手坐标系
#   - X 轴沿目标长度方向，但其具体指向受以下 orientation_availability 约束
#   - Y 轴沿目标宽度方向
#   - Z 轴沿目标高度方向，指向上方
#
# 7. dimensions 和 footprint 在目标局部坐标系中定义。
#    footprint 不是 指定参考的坐标系下 的坐标；应结合 pose 转换到 指定参考的坐标系下。
#
# 8. 单位遵循 ROS 约定：
#    - 位置、尺寸：m
#    - 线速度：m/s
#    - 角速度：rad/s
#    - 线加速度：m/s^2
#    - 角加速度：rad/s^2
# ============================================================


# 1. 基础属性
uuid_msgs/UniqueID object_id           # 全局唯一的追踪 ID，轨迹删除后，不应立即复用相同 ID

ObjectClassification classification    # 当前目标置信度最高的最终语义类别

# ============================================================
# 2. 跟踪状态
# ============================================================

# TRACK_UNKNOWN：未知
# TENTATIVE：单帧新增障碍物/持续多帧尚未满足稳定确认条件，防止目标漏避
# CONFIRMED：稳定轨迹，当前有观测更新
# COASTED：当前无观测，由运动模型预测外推

uint8 TRACK_UNKNOWN=0
uint8 TRACK_TENTATIVE=1
# 当前版本的感知发布端仅输出 TRACK_CONFIRMED。
uint8 TRACK_CONFIRMED=2
uint8 TRACK_COASTED=3

uint8 track_state

# 自轨迹创建以来的持续时间，单位 s
float32 tracking_time

# 距最后一次真实观测更新的时间，单位 s
float32 time_since_update

# ==========================================
# 3. 运动学状态 (Kinematics)
# 包含了位姿、速度、加速度，以及它们对应的 6x6 协方差矩阵(表示不确定性)
# ==========================================

# 位姿 (x, y, z 及 四元数姿态) + 协方差
geometry_msgs/PoseWithCovariance pose
bool has_pose_covariance

# 速度 (线速度 v_x, v_y, v_z 及 角速度) + 协方差
geometry_msgs/TwistWithCovariance twist
bool has_linear_velocity 
bool has_angular_velocity 
bool has_linear_covariance
bool has_angular_covariance

# 加速度 (线加速度 a_x, a_y, a_z 及 角加速度) + 协方差
geometry_msgs/AccelWithCovariance acceleration
bool has_acceleration
bool has_acceleration_covariance

# 运动状态

uint8 MOTION_UNKNOWN=0
uint8 MOTION_MOVING=1
uint8 MOTION_STATIONARY=2

uint8 motion_state

# ============================================================
# 4. 朝向有效性
# ============================================================

# 无法获得可靠的几何方向或语义朝向。
# pose.orientation 必须是合法且归一化的四元数；
# 没有任何方向估计时推荐填单位四元数。
#
# 当 shape_type=SHAPE_BOUNDING_BOX 时，应输出相对于
# header.frame_id 的轴对齐保守包围盒，或改用不依赖朝向的
# SHAPE_CYLINDER。
uint8 ORIENTATION_UNAVAILABLE=0

# 只能确定目标长轴，正反方向存在 pi 弧度二义性。
# 局部 X 轴平行于目标长轴，但正方向可能与真实前方相反。
uint8 ORIENTATION_SIGN_UNKNOWN=1

# 能够完整区分目标正面和背面，局部 +X 指向前方，+Y 指向左侧，+Z 指向上方。
uint8 ORIENTATION_AVAILABLE=2

uint8 orientation_availability



# ==========================================
# 5. 几何形状 (Shape)
# 局部 x 轴为 length 方向，局部 y 轴为 width 方向，局部 z 轴为 height 方向
# polygon 点序为逆时针，首尾点闭合
# ==========================================
# 形状未知或当前无法提供可靠几何形状 
uint8 SHAPE_UNKNOWN=0
uint8 SHAPE_BOUNDING_BOX=1
uint8 SHAPE_CYLINDER=2
uint8 SHAPE_POLYGON=3

uint8 shape_type                       # 形状类型

#BOUNDING_BOX：x=length, y=width, z=height，且 footprint 应为空
#CYLINDER：x=diameter, y=diameter, z=height，且 footprint 应为空
#POLYGON：x=0, y=0, z=height，形状由 footprint 决定
geometry_msgs/Vector3 dimensions

# 仅在 shape_type=SHAPE_POLYGON 时使用；
# 点位于目标局部坐标系中
geometry_msgs/Polygon footprint

================================================================================
MSG: uuid_msgs/UniqueID
# A universally unique identifier (UUID).
#
#  http://en.wikipedia.org/wiki/Universally_unique_identifier
#  http://tools.ietf.org/html/rfc4122.html

uint8[16] uuid

================================================================================
MSG: dynamic_obstacles/ObjectClassification
# ObjectClassification.msg
#
# 类别编号按类别族分段预留。
# 已发布的类别编号不得改变，新增类别应使用对应预留区间。
#
# 0       ：未知类别
# 10~29   ：道路车辆
# 30~49   ：两轮或三轮车辆
# 50~69   ：行人
# 70~89   ：动物
# 90~109  ：交通设施及危险物
# 110~253 ：后续类别预留
# 254     ：其他类别
# 255     ：非法或不支持的类别


# 无法可靠识别类别，但目标仍可能真实存在，需要正常避障
uint8 UNKNOWN=0


# ============================================================
# 道路车辆：10~29
# ============================================================

# 小型乘用车辆，如轿车、SUV、MPV
uint8 CAR=10

# 货运车辆，如轻卡、厢式货车、重型卡车
uint8 TRUCK=11

# 载客大型车辆，如公交车、大巴、中巴
uint8 BUS=12

# 被牵引的挂车或拖车部分
uint8 TRAILER=13

# 14~29 预留给其他道路车辆
# 例如：VAN、FORKLIFT、CONSTRUCTION_VEHICLE


# ============================================================
# 两轮或三轮车辆：30~49
# ============================================================

# 摩托车、电动摩托车等机动车辆
uint8 MOTORCYCLE=30

# 普通脚踏自行车
uint8 BICYCLE=31

# 电动自行车，不包括电动摩托车
uint8 ELECTRIC_BICYCLE=32

# 33~49 预留
# 例如：TRICYCLE


# ============================================================
# 人：50~69
# ============================================================

# 普通人(无法进一步区分的人)。
uint8 PEDESTRIAN=50

#儿童
uint8 CHILD=51

#轮椅用户，需要更大的横向安全距离，且运动学模型与正常行人不同
uint8 WHEELCHAIR=52

# ============================================================
# 动物：70~89
# ============================================================
# 狗、猫等动物
uint8 ANIMAL=70


# ============================================================
# 交通设施及危险物：90~109
# ============================================================

# 交通锥、锥桶
uint8 TRAFFIC_CONE=90

# 闸机横杆
uint8 BOOM_BARRIER=91

# 门/闸机，此类障碍物的状态是可变的（开/关）
uint8 DOOR_GATE=92

# 93~109 预留
# 例如：BARRIER、BOLLARD、ROADBLOCK、DEBRIS


# ============================================================
# 特殊值
# ============================================================
# 已确认不属于当前已定义类别的其他目标。
# 若无法识别类别，应使用 UNKNOWN。
uint8 OTHER=254

# 非法、解析失败或接口不支持的类别
# 正常感知结果不应输出该值
uint8 INVALID=255


# 目标语义类别
uint8 label

# 当前类别的分类概率，范围 [0.0, 1.0]
# 不等同于目标存在概率 existence_probability
float32 probability


================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/AccelWithCovariance
# This expresses acceleration in free space with uncertainty.

Accel accel

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Polygon
#A specification of a polygon where the first and last points are assumed to be connected
Point32[] points

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  # Pseudo-constants
  TRACK_UNKNOWN = 0
  TRACK_TENTATIVE = 1
  TRACK_CONFIRMED = 2
  TRACK_COASTED = 3
  MOTION_UNKNOWN = 0
  MOTION_MOVING = 1
  MOTION_STATIONARY = 2
  ORIENTATION_UNAVAILABLE = 0
  ORIENTATION_SIGN_UNKNOWN = 1
  ORIENTATION_AVAILABLE = 2
  SHAPE_UNKNOWN = 0
  SHAPE_BOUNDING_BOX = 1
  SHAPE_CYLINDER = 2
  SHAPE_POLYGON = 3

  __slots__ = ['object_id','classification','track_state','tracking_time','time_since_update','pose','has_pose_covariance','twist','has_linear_velocity','has_angular_velocity','has_linear_covariance','has_angular_covariance','acceleration','has_acceleration','has_acceleration_covariance','motion_state','orientation_availability','shape_type','dimensions','footprint']
  _slot_types = ['uuid_msgs/UniqueID','dynamic_obstacles/ObjectClassification','uint8','float32','float32','geometry_msgs/PoseWithCovariance','bool','geometry_msgs/TwistWithCovariance','bool','bool','bool','bool','geometry_msgs/AccelWithCovariance','bool','bool','uint8','uint8','uint8','geometry_msgs/Vector3','geometry_msgs/Polygon']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_id,classification,track_state,tracking_time,time_since_update,pose,has_pose_covariance,twist,has_linear_velocity,has_angular_velocity,has_linear_covariance,has_angular_covariance,acceleration,has_acceleration,has_acceleration_covariance,motion_state,orientation_availability,shape_type,dimensions,footprint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrackedObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.object_id is None:
        self.object_id = uuid_msgs.msg.UniqueID()
      if self.classification is None:
        self.classification = dynamic_obstacles.msg.ObjectClassification()
      if self.track_state is None:
        self.track_state = 0
      if self.tracking_time is None:
        self.tracking_time = 0.
      if self.time_since_update is None:
        self.time_since_update = 0.
      if self.pose is None:
        self.pose = geometry_msgs.msg.PoseWithCovariance()
      if self.has_pose_covariance is None:
        self.has_pose_covariance = False
      if self.twist is None:
        self.twist = geometry_msgs.msg.TwistWithCovariance()
      if self.has_linear_velocity is None:
        self.has_linear_velocity = False
      if self.has_angular_velocity is None:
        self.has_angular_velocity = False
      if self.has_linear_covariance is None:
        self.has_linear_covariance = False
      if self.has_angular_covariance is None:
        self.has_angular_covariance = False
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.AccelWithCovariance()
      if self.has_acceleration is None:
        self.has_acceleration = False
      if self.has_acceleration_covariance is None:
        self.has_acceleration_covariance = False
      if self.motion_state is None:
        self.motion_state = 0
      if self.orientation_availability is None:
        self.orientation_availability = 0
      if self.shape_type is None:
        self.shape_type = 0
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.footprint is None:
        self.footprint = geometry_msgs.msg.Polygon()
    else:
      self.object_id = uuid_msgs.msg.UniqueID()
      self.classification = dynamic_obstacles.msg.ObjectClassification()
      self.track_state = 0
      self.tracking_time = 0.
      self.time_since_update = 0.
      self.pose = geometry_msgs.msg.PoseWithCovariance()
      self.has_pose_covariance = False
      self.twist = geometry_msgs.msg.TwistWithCovariance()
      self.has_linear_velocity = False
      self.has_angular_velocity = False
      self.has_linear_covariance = False
      self.has_angular_covariance = False
      self.acceleration = geometry_msgs.msg.AccelWithCovariance()
      self.has_acceleration = False
      self.has_acceleration_covariance = False
      self.motion_state = 0
      self.orientation_availability = 0
      self.shape_type = 0
      self.dimensions = geometry_msgs.msg.Vector3()
      self.footprint = geometry_msgs.msg.Polygon()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.object_id.uuid
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_16B().pack(*_x))
      else:
        buff.write(_get_struct_16s().pack(_x))
      _x = self
      buff.write(_get_struct_BfB2f7d().pack(_x.classification.label, _x.classification.probability, _x.track_state, _x.tracking_time, _x.time_since_update, _x.pose.pose.position.x, _x.pose.pose.position.y, _x.pose.pose.position.z, _x.pose.pose.orientation.x, _x.pose.pose.orientation.y, _x.pose.pose.orientation.z, _x.pose.pose.orientation.w))
      buff.write(_get_struct_36d().pack(*self.pose.covariance))
      _x = self
      buff.write(_get_struct_B6d().pack(_x.has_pose_covariance, _x.twist.twist.linear.x, _x.twist.twist.linear.y, _x.twist.twist.linear.z, _x.twist.twist.angular.x, _x.twist.twist.angular.y, _x.twist.twist.angular.z))
      buff.write(_get_struct_36d().pack(*self.twist.covariance))
      _x = self
      buff.write(_get_struct_4B6d().pack(_x.has_linear_velocity, _x.has_angular_velocity, _x.has_linear_covariance, _x.has_angular_covariance, _x.acceleration.accel.linear.x, _x.acceleration.accel.linear.y, _x.acceleration.accel.linear.z, _x.acceleration.accel.angular.x, _x.acceleration.accel.angular.y, _x.acceleration.accel.angular.z))
      buff.write(_get_struct_36d().pack(*self.acceleration.covariance))
      _x = self
      buff.write(_get_struct_5B3d().pack(_x.has_acceleration, _x.has_acceleration_covariance, _x.motion_state, _x.orientation_availability, _x.shape_type, _x.dimensions.x, _x.dimensions.y, _x.dimensions.z))
      length = len(self.footprint.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.footprint.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.object_id is None:
        self.object_id = uuid_msgs.msg.UniqueID()
      if self.classification is None:
        self.classification = dynamic_obstacles.msg.ObjectClassification()
      if self.pose is None:
        self.pose = geometry_msgs.msg.PoseWithCovariance()
      if self.twist is None:
        self.twist = geometry_msgs.msg.TwistWithCovariance()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.AccelWithCovariance()
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.footprint is None:
        self.footprint = geometry_msgs.msg.Polygon()
      end = 0
      start = end
      end += 16
      self.object_id.uuid = str[start:end]
      _x = self
      start = end
      end += 70
      (_x.classification.label, _x.classification.probability, _x.track_state, _x.tracking_time, _x.time_since_update, _x.pose.pose.position.x, _x.pose.pose.position.y, _x.pose.pose.position.z, _x.pose.pose.orientation.x, _x.pose.pose.orientation.y, _x.pose.pose.orientation.z, _x.pose.pose.orientation.w,) = _get_struct_BfB2f7d().unpack(str[start:end])
      start = end
      end += 288
      self.pose.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 49
      (_x.has_pose_covariance, _x.twist.twist.linear.x, _x.twist.twist.linear.y, _x.twist.twist.linear.z, _x.twist.twist.angular.x, _x.twist.twist.angular.y, _x.twist.twist.angular.z,) = _get_struct_B6d().unpack(str[start:end])
      self.has_pose_covariance = bool(self.has_pose_covariance)
      start = end
      end += 288
      self.twist.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 52
      (_x.has_linear_velocity, _x.has_angular_velocity, _x.has_linear_covariance, _x.has_angular_covariance, _x.acceleration.accel.linear.x, _x.acceleration.accel.linear.y, _x.acceleration.accel.linear.z, _x.acceleration.accel.angular.x, _x.acceleration.accel.angular.y, _x.acceleration.accel.angular.z,) = _get_struct_4B6d().unpack(str[start:end])
      self.has_linear_velocity = bool(self.has_linear_velocity)
      self.has_angular_velocity = bool(self.has_angular_velocity)
      self.has_linear_covariance = bool(self.has_linear_covariance)
      self.has_angular_covariance = bool(self.has_angular_covariance)
      start = end
      end += 288
      self.acceleration.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 29
      (_x.has_acceleration, _x.has_acceleration_covariance, _x.motion_state, _x.orientation_availability, _x.shape_type, _x.dimensions.x, _x.dimensions.y, _x.dimensions.z,) = _get_struct_5B3d().unpack(str[start:end])
      self.has_acceleration = bool(self.has_acceleration)
      self.has_acceleration_covariance = bool(self.has_acceleration_covariance)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.footprint.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.footprint.points.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.object_id.uuid
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_16B().pack(*_x))
      else:
        buff.write(_get_struct_16s().pack(_x))
      _x = self
      buff.write(_get_struct_BfB2f7d().pack(_x.classification.label, _x.classification.probability, _x.track_state, _x.tracking_time, _x.time_since_update, _x.pose.pose.position.x, _x.pose.pose.position.y, _x.pose.pose.position.z, _x.pose.pose.orientation.x, _x.pose.pose.orientation.y, _x.pose.pose.orientation.z, _x.pose.pose.orientation.w))
      buff.write(self.pose.covariance.tostring())
      _x = self
      buff.write(_get_struct_B6d().pack(_x.has_pose_covariance, _x.twist.twist.linear.x, _x.twist.twist.linear.y, _x.twist.twist.linear.z, _x.twist.twist.angular.x, _x.twist.twist.angular.y, _x.twist.twist.angular.z))
      buff.write(self.twist.covariance.tostring())
      _x = self
      buff.write(_get_struct_4B6d().pack(_x.has_linear_velocity, _x.has_angular_velocity, _x.has_linear_covariance, _x.has_angular_covariance, _x.acceleration.accel.linear.x, _x.acceleration.accel.linear.y, _x.acceleration.accel.linear.z, _x.acceleration.accel.angular.x, _x.acceleration.accel.angular.y, _x.acceleration.accel.angular.z))
      buff.write(self.acceleration.covariance.tostring())
      _x = self
      buff.write(_get_struct_5B3d().pack(_x.has_acceleration, _x.has_acceleration_covariance, _x.motion_state, _x.orientation_availability, _x.shape_type, _x.dimensions.x, _x.dimensions.y, _x.dimensions.z))
      length = len(self.footprint.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.footprint.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.object_id is None:
        self.object_id = uuid_msgs.msg.UniqueID()
      if self.classification is None:
        self.classification = dynamic_obstacles.msg.ObjectClassification()
      if self.pose is None:
        self.pose = geometry_msgs.msg.PoseWithCovariance()
      if self.twist is None:
        self.twist = geometry_msgs.msg.TwistWithCovariance()
      if self.acceleration is None:
        self.acceleration = geometry_msgs.msg.AccelWithCovariance()
      if self.dimensions is None:
        self.dimensions = geometry_msgs.msg.Vector3()
      if self.footprint is None:
        self.footprint = geometry_msgs.msg.Polygon()
      end = 0
      start = end
      end += 16
      self.object_id.uuid = str[start:end]
      _x = self
      start = end
      end += 70
      (_x.classification.label, _x.classification.probability, _x.track_state, _x.tracking_time, _x.time_since_update, _x.pose.pose.position.x, _x.pose.pose.position.y, _x.pose.pose.position.z, _x.pose.pose.orientation.x, _x.pose.pose.orientation.y, _x.pose.pose.orientation.z, _x.pose.pose.orientation.w,) = _get_struct_BfB2f7d().unpack(str[start:end])
      start = end
      end += 288
      self.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 49
      (_x.has_pose_covariance, _x.twist.twist.linear.x, _x.twist.twist.linear.y, _x.twist.twist.linear.z, _x.twist.twist.angular.x, _x.twist.twist.angular.y, _x.twist.twist.angular.z,) = _get_struct_B6d().unpack(str[start:end])
      self.has_pose_covariance = bool(self.has_pose_covariance)
      start = end
      end += 288
      self.twist.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 52
      (_x.has_linear_velocity, _x.has_angular_velocity, _x.has_linear_covariance, _x.has_angular_covariance, _x.acceleration.accel.linear.x, _x.acceleration.accel.linear.y, _x.acceleration.accel.linear.z, _x.acceleration.accel.angular.x, _x.acceleration.accel.angular.y, _x.acceleration.accel.angular.z,) = _get_struct_4B6d().unpack(str[start:end])
      self.has_linear_velocity = bool(self.has_linear_velocity)
      self.has_angular_velocity = bool(self.has_angular_velocity)
      self.has_linear_covariance = bool(self.has_linear_covariance)
      self.has_angular_covariance = bool(self.has_angular_covariance)
      start = end
      end += 288
      self.acceleration.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 29
      (_x.has_acceleration, _x.has_acceleration_covariance, _x.motion_state, _x.orientation_availability, _x.shape_type, _x.dimensions.x, _x.dimensions.y, _x.dimensions.z,) = _get_struct_5B3d().unpack(str[start:end])
      self.has_acceleration = bool(self.has_acceleration)
      self.has_acceleration_covariance = bool(self.has_acceleration_covariance)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.footprint.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.footprint.points.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16B = None
def _get_struct_16B():
    global _struct_16B
    if _struct_16B is None:
        _struct_16B = struct.Struct("<16B")
    return _struct_16B
_struct_16s = None
def _get_struct_16s():
    global _struct_16s
    if _struct_16s is None:
        _struct_16s = struct.Struct("<16s")
    return _struct_16s
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4B6d = None
def _get_struct_4B6d():
    global _struct_4B6d
    if _struct_4B6d is None:
        _struct_4B6d = struct.Struct("<4B6d")
    return _struct_4B6d
_struct_5B3d = None
def _get_struct_5B3d():
    global _struct_5B3d
    if _struct_5B3d is None:
        _struct_5B3d = struct.Struct("<5B3d")
    return _struct_5B3d
_struct_B6d = None
def _get_struct_B6d():
    global _struct_B6d
    if _struct_B6d is None:
        _struct_B6d = struct.Struct("<B6d")
    return _struct_B6d
_struct_BfB2f7d = None
def _get_struct_BfB2f7d():
    global _struct_BfB2f7d
    if _struct_BfB2f7d is None:
        _struct_BfB2f7d = struct.Struct("<BfB2f7d")
    return _struct_BfB2f7d
