# mpc
receding: 4
step_time: 0.3
ref_speed: 1.0
device: 'cpu'
time_print: False
collision_threshold: 0.01

# robot
robot:
  kinematics: 'diff'
  max_speed: [1.5, 1]
  max_acce: [1, 1]
  length: 0.7
  width: 0.5

# initial path
ipath:
  interval: 0.1
  waypoints: [[0, 0, 0], [5, 0, 0]]
  curve_style: 'line'   # 'dubins' or reeds or line
  min_radius: 0.0
  loop: False
  arrive_threshold: 0.4
  close_threshold: 0.1
  arrive_index_threshold: 0 # end of the path
  
# proximal alternating minimization network
pan:
  iter_num: 1
  dune_max_num: 60
  nrmp_max_num: 6
  dune_checkpoint: None
  iter_threshold: 0.1

# adjust parameters
adjust:
  q_s: 0.3
  p_u: 1.5
  eta: 10.0
  d_max: 0.15
  d_min: 0.01
