# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dynamic_obstacles/ObjectClassification.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ObjectClassification(genpy.Message):
  _md5sum = "b67f0ffe50a7c47e827671307d1e4a55"
  _type = "dynamic_obstacles/ObjectClassification"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ObjectClassification.msg
#
# 类别编号按类别族分段预留。
# 已发布的类别编号不得改变，新增类别应使用对应预留区间。
#
# 0       ：未知类别
# 10~29   ：道路车辆
# 30~49   ：两轮或三轮车辆
# 50~69   ：行人
# 70~89   ：动物
# 90~109  ：交通设施及危险物
# 110~253 ：后续类别预留
# 254     ：其他类别
# 255     ：非法或不支持的类别


# 无法可靠识别类别，但目标仍可能真实存在，需要正常避障
uint8 UNKNOWN=0


# ============================================================
# 道路车辆：10~29
# ============================================================

# 小型乘用车辆，如轿车、SUV、MPV
uint8 CAR=10

# 货运车辆，如轻卡、厢式货车、重型卡车
uint8 TRUCK=11

# 载客大型车辆，如公交车、大巴、中巴
uint8 BUS=12

# 被牵引的挂车或拖车部分
uint8 TRAILER=13

# 14~29 预留给其他道路车辆
# 例如：VAN、FORKLIFT、CONSTRUCTION_VEHICLE


# ============================================================
# 两轮或三轮车辆：30~49
# ============================================================

# 摩托车、电动摩托车等机动车辆
uint8 MOTORCYCLE=30

# 普通脚踏自行车
uint8 BICYCLE=31

# 电动自行车，不包括电动摩托车
uint8 ELECTRIC_BICYCLE=32

# 33~49 预留
# 例如：TRICYCLE


# ============================================================
# 人：50~69
# ============================================================

# 普通人(无法进一步区分的人)。
uint8 PEDESTRIAN=50

#儿童
uint8 CHILD=51

#轮椅用户，需要更大的横向安全距离，且运动学模型与正常行人不同
uint8 WHEELCHAIR=52

# ============================================================
# 动物：70~89
# ============================================================
# 狗、猫等动物
uint8 ANIMAL=70


# ============================================================
# 交通设施及危险物：90~109
# ============================================================

# 交通锥、锥桶
uint8 TRAFFIC_CONE=90

# 闸机横杆
uint8 BOOM_BARRIER=91

# 门/闸机，此类障碍物的状态是可变的（开/关）
uint8 DOOR_GATE=92

# 93~109 预留
# 例如：BARRIER、BOLLARD、ROADBLOCK、DEBRIS


# ============================================================
# 特殊值
# ============================================================
# 已确认不属于当前已定义类别的其他目标。
# 若无法识别类别，应使用 UNKNOWN。
uint8 OTHER=254

# 非法、解析失败或接口不支持的类别
# 正常感知结果不应输出该值
uint8 INVALID=255


# 目标语义类别
uint8 label

# 当前类别的分类概率，范围 [0.0, 1.0]
# 不等同于目标存在概率 existence_probability
float32 probability

"""
  # Pseudo-constants
  UNKNOWN = 0
  CAR = 10
  TRUCK = 11
  BUS = 12
  TRAILER = 13
  MOTORCYCLE = 30
  BICYCLE = 31
  ELECTRIC_BICYCLE = 32
  PEDESTRIAN = 50
  CHILD = 51
  WHEELCHAIR = 52
  ANIMAL = 70
  TRAFFIC_CONE = 90
  BOOM_BARRIER = 91
  DOOR_GATE = 92
  OTHER = 254
  INVALID = 255

  __slots__ = ['label','probability']
  _slot_types = ['uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       label,probability

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectClassification, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.label is None:
        self.label = 0
      if self.probability is None:
        self.probability = 0.
    else:
      self.label = 0
      self.probability = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bf().pack(_x.label, _x.probability))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.label, _x.probability,) = _get_struct_Bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bf().pack(_x.label, _x.probability))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.label, _x.probability,) = _get_struct_Bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bf = None
def _get_struct_Bf():
    global _struct_Bf
    if _struct_Bf is None:
        _struct_Bf = struct.Struct("<Bf")
    return _struct_Bf
